# Generated by Django 2.2 on 2020-11-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
    ]
