# Generated by Django 2.2 on 2020-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201126_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟数）'),
        ),
        migrations.AlterField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟数）'),
        ),
    ]
