# Generated by Django 2.2 on 2020-11-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20201118_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='cileck_nums',
            new_name='click_nums',
        ),
    ]
